# -*- coding: utf-8 -*

US_LCI = {
    "Bark, hardwood, average, at forest road, NE-NC": "Bark, hardwood, average, at forest road,  NE-NC",
    "Bucked log, hardwood, green, at veneer mill, E": "Bucked and debarked log, hardwood, green, at veneer mill, E",
    "Chlorine, PVC producer average, at plant": "Chlor-alkali electrolysis, average production mix, at plant",  # Best guess?
    "Compressed natural gas, at plant": "Natural gas, processed, at plant",
    "Corn stover, production, average,US, 2022": "Corn stover, production, average, US, 2022",
    "corn wet milling operations, AP-42": "corn wet milling, operations, AP-42",
    "Electricity, as grid, US, 2008": "Electricity, at Grid, US, 2008",
    "Electricity, at cogen, natural gas turbine": "Electricity, at cogen, for natural gas turbine",
    "Electricity, at grid, Eastern US": "Electricity, at grid, Eastern US, 2000",
    "Electricity, at grid, US": "Electricity, at Grid, US, 2008",
    "Electricity, at grid, Western US": "Electricity, at grid, Western US, 2000",
    "Electricity, cogenerated, at plant": "Electricity, at cogen, for natural gas turbine",  # Best guess?
    "Electricity, onsite boiler, hardwood mill average, SE": "Electricity, onsite boiler, hardwood mill, average, SE",
    "Electricity, onsite boiler, hardwood mill, average, NE-NC": "Electricity, onsite boiler, hardwood mill average, NE-NC",
    "Electricity, onsite boiler, softwood mill average, NE-NC": "Electricity, onsite boiler, softwood mill, average, NE-NC",
    "ethanol, denatured, forest residues, thermochemical": "Ethanol, denatured, forest residues, thermochem",
    "Fuel wood, hardwood, green, at veneer mill, E": "Wood fuel, hardwood, green, at veneer mill, E",
    "Head, indirect, heated zones, softwood, plywood veneer drying, AP-42": "indirect heated, heated zones, softwood, plywood veneer drying, AP-42",
    "Heat, Block conditioning, at veneer mill, E": "Heat, block conditiong, at veneer mill, E",
    "Heat, Drying veneer, hardwood, at veneer mill,  E": "Heat, drying veneer, hardwood, at veneer mill, E",
    "Heat, onsite boiler, hardwood mill average, SE": "Heat, onsite boiler, hardwood mill, average, SE",
    "Heat, onsite boiler, hardwood mill, average, NE-NC": "Heat, onsite boiler, hardwood mill average, NE-NC",
    "Natural gas, processed, for olefins production, at plant, internal offgas use": "Natural gas, processed, for olefins production, at plant",
    "Natural gas, processed, for olefins production, at plant, material use": "Natural gas, processed, for olefins production, at plant",
    "Palm kernel oil, crude, at plant": "Crude palm kernel oil, at plant",
    "Petroleum refining, for olefins production, at plant, internal offgas use": "Petroleum refining, for olefins production, at plant",
    "Petroleum refining, for olefins production, at plant, material use": "Petroleum refining, for olefins production, at plant",
    "Sawn lumber, hardwood, rough, kiln dried, at kiln, NE-NC  ": "Sawn lumber, hardwood, rough, kiln dried, at kiln, NE-NC",
    "Spring wheat straw, ground and stored": "spring wheat straw, ground and stored, 2022",
    "Switchgrass, production, average, US, 2022": "Switchgrass, production, US, 2022",
    "tillage, corn, conservation": "tillage, conversation, corn production",
    "tillage, corn, intensive": "tillage, intensive, corn production",
    "tillage, corn, reduced": "tillage, reduce, corn production",
    "Transport, combination truck": "Transport, combination truck, average fuel mix",
    "Transport, combination truck, diesel powered ": "Transport, combination truck, diesel powered",
    "Transport, ocean tanker, average fuel mix": "Transport, ocean freighter, average fuel mix",
    "Transport, pipeline, unspecified": "Transport, pipeline, unspecified petroleum products",
    "Transport, single-unit truck": "Transport, single unit truck, diesel powered",  # No average fuel mix - guess for diesel?
    "Wood, hardwood, generated at mill, combusted in industrial boiler, E": "Wood fuel, E hardwood, generated at mill, combusted in industrial boiler",
    "Wood, hardwood, purchased, combusted in industrial boiler, E": "Wood fuel, E hardwood, purchased, combusted in industrial boiler, E",
    "Wood, NE-NC hardwood, generated at lumber mill, combusted in industrial boiler": "Wood fuel, NE-NC hardwood, gen at lumber mill, combusted in industrial boiler",
    "Wood, NE-NC hardwood, purchased, combusted in industrial boiler": "Wood fuel, NE-NC hardwood, purchased, combusted in industrial boiler",
    'decomposition, corn, 15.5% moisture basis': "Corn, decomposition, 15.5% moisture",
}
